version: '3.1'

services:
  postgres:
    image: postgres:15.3
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: aGVsBTGYhBPjFXCz
    volumes:
      - familybook-postgres-data:/var/lib/postgresql/data
      - ./postgres/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql

volumes:
  familybook-postgres-data:
